---
title: フロー実行の一時停止と再開
description: フロー実行を一時停止、中断、再開するさまざまな方法を学習します。
---

Prefect では、似ているもののわずかに異なる 2 つの関数を使用してフロー実行を停止できます。
フロー実行が一時停止されると、コード実行は停止されますが、プロセスは実行を継続します。
フロー実行が中断されると、コード実行が停止され、プロセスも停止します。

### フロー実行を一時停止する

Prefect では、進行中のフロー実行を一時停止して手動で承認を求めることができます。
Prefect はこの機能を [`pause_flow_run`](https://reference.prefect.io/prefect/engine/#prefect.engine.pause_flow_run) 関数と [`resume_flow_run`](https://reference.prefect.io/prefect/engine/#prefect.engine.resume_flow_run) 関数で提供しています。

<Note>
**タイムアウト**

一時停止中のフロー実行は、デフォルトで1時間後にタイムアウトします。
タイムアウト後、フロー実行は失敗し、一時停止したまま再開されなかったことを示すメッセージが表示されます。
`timeout` パラメータを使用して、異なるタイムアウト期間を秒単位で指定できます。
</Note>

フロー内で `pause_flow_run` を呼び出すことができます:

```python
from prefect import task, flow, pause_flow_run, resume_flow_run

@task
async def marvin_setup():
    return "a raft of ducks walk into a bar..."


@task
async def marvin_punchline():
    return "it's a wonder none of them ducked!"


@flow
async def inspiring_joke():
    await marvin_setup()
    await pause_flow_run(timeout=600)  # pauses for 10 minutes
    await marvin_punchline()
```

条件付きの一時停止を実装することもできます:

```python
from prefect import task, flow, pause_flow_run

@task
def task_one():
    for i in range(3):
        sleep(1)
        print(i)

@flow(log_prints=True)
def my_flow():
    terminal_state = task_one.submit(return_state=True)
    if terminal_state.type == StateType.COMPLETED:
        print("Task one succeeded! Pausing flow run..")
        pause_flow_run(timeout=2)
    else:
        print("Task one failed. Skipping pause flow run..")
```

このフローを呼び出すと、最初のタスクの後のコード実行がブロックされ、パンチラインの配信の再開を待機します。

```bash
await inspiring_joke()
> "a raft of ducks walk into a bar..."
```

一時停止されたフローの実行を再開するには、Prefect UI で [**再開**] をクリックするか、クライアント コードを通じて `resume_flow_run` ユーティリティを呼び出します。

{/* pmd-metadata: notest */}
```python
from prefect import resume_flow_run

resume_flow_run(FLOW_RUN_ID)
```

一時停止されたフローの実行は終了します。

```
> "it's a wonder none of them ducked!"
```

### フロー実行を一時停止する

フロー実行を一時停止するのと同様に、Prefect では進行中のフロー実行を一時停止できます。

<Note>
**フロー実行の一時停止と中断の違い**

フロー実行の一時停止と中断には重要な違いがあります。
フロー実行を一時停止すると、フローコードは引き続き実行されますが、誰かがフローを再開するまでブロックされます。
これは、フロー実行の中断には当てはまりません。
フロー実行を中断すると、フローは完全に終了し、それを実行しているインフラストラクチャ（Kubernetes ジョブなど）は破棄されます。
</Note>

つまり、長時間実行されるインフラストラクチャの費用を節約するために、フロー実行を一時停止することができます。
ただし、フロー実行が再開されると、フローコードはフローの先頭から再度実行されます。
高コストな操作の再計算を避けるため、[タスク](/v3/develop/write-tasks/)と[タスクキャッシュ](/v3/develop/task-caching)を使用することをお勧めします。

Prefectは、この機能を[`suspend_flow_run`](https://reference.prefect.io/prefect/engine/#prefect.engine.suspend_flow_run)関数と[`resume_flow_run`](https://reference.prefect.io/prefect/engine/#prefect.engine.resume_flow_run)関数、およびPrefect UIを通じて提供しています。

フロー内で呼び出されると、`suspend_flow_run`はフロー実行の実行を直ちに一時停止します。
フロー実行は「Suspended」としてマークされており、「resume_flow_run」が呼び出されるまで再開されません。

<Note>
**タイムアウト**

一時停止されたフロー実行は、デフォルトで1時間後にタイムアウトします。
タイムアウト後、フロー実行は失敗し、一時停止され再開されなかったことを示すメッセージが表示されます。
`timeout` パラメータを使用して、異なるタイムアウト時間を秒単位で指定するか、`timeout=None` を渡してタイムアウトなしとすることもできます。
</Note>

以下は、一時停止中にフローの実行をブロックしないフローの例です。
このフローは 1 つのタスクの後に終了し、再開時に再スケジュールされます。
最初のタスクの保存された結果は、再実行されずに取得されます。

```python
from prefect import flow, pause_flow_run, task

@task(persist_result=True)
def foo():
    return 42

@flow(persist_result=True)
def noblock_pausing():
    x = foo.submit()
    pause_flow_run(timeout=30, reschedule=True)
    y = foo.submit()
    z = foo(wait_for=[x])
    alpha = foo(wait_for=[y])
    omega = foo(wait_for=[x, y])
```

アウトオブプロセスでフロー実行を一時停止するには、`suspend_flow_run(flow_run_id=<ID>)` を呼び出すか、Prefect UI または Prefect Cloud で **Suspend** ボタンを選択します。

一時停止したフロー実行を再開するには、Prefect UI で **Resume** をクリックするか、クライアントコードから `resume_flow_run` ユーティリティを呼び出します。

{/* pmd-metadata: notest */}
```python
from prefect import resume_flow_run

resume_flow_run(FLOW_RUN_ID)
```
<Note>

**親フローの実行とは独立してサブフローを一時停止することはできません**

`run_deployment` を使ってフロー実行をスケジュールする場合、スケジュールされたフロー実行は、デフォルトで呼び出し元フローにネストされたフロー実行としてリンクされます。
つまり、呼び出し元フローとは独立してスケジュールされたフロー実行を一時停止することはできません。

呼び出し元フローとは独立してスケジュールされたフロー実行を一時停止する必要がある場合は、`as_subflow=False` を指定して `run_deployment` を呼び出し、このリンクを無効にしてください。
</Note>

## フロー実行を一時停止または中断するときに入力を待機する

<Warning>
**試験的**

`pause_flow_run` または `suspend_flow_run` 関数で使用される `wait_for_input` パラメータは試験的な機能です。
この機能のインターフェースまたは動作は、将来のリリースで予告なく変更される可能性があります。

問題が発生した場合は、Slack または GitHub の Issue でお知らせください。
</Warning>

フロー実行を一時停止または中断する際に、ユーザーからの入力を待機する必要がある場合があります。
Prefect では、`pause_flow_run` 関数と `suspend_flow_run` 関数を使用することで、これを実現できます。
これらの関数は `wait_for_input` 引数を受け取ります。この引数は、`prefect.input.RunInput`（Pydantic モデル）のサブクラスである必要があります。
フロー実行を再開する際には、ユーザーはこのモデルにデータを入力する必要があります。検証が成功すると、フロー実行が再開され、`pause_flow_run` または `suspend_flow_run` の戻り値は、入力されたデータを含むモデルのインスタンスになります。

以下は、一時停止してユーザーからの入力を待機するフローの例です。

```python
from prefect import flow, pause_flow_run
from prefect.input import RunInput


class UserNameInput(RunInput):
    name: str


@flow(log_prints=True)
async def greet_user():
    user_input = await pause_flow_run(
        wait_for_input=UserNameInput
    )

    print(f"Hello, {user_input.name}!")
```

このフローを実行すると、フロー実行が作成されます。フロー実行は、コード実行が `pause_flow_run` に到達するまで進行し、その時点で `Paused` 状態に移行します。
実行はブロックされ、再開を待機します。

フロー実行を再開すると、ユーザーは `UserNameInput` モデルの `name` フィールドに値を入力するよう求められます。
検証が成功すると、フロー実行が再開され、`pause_flow_run` の戻り値は、入力されたデータを含む `UserNameInput` モデルのインスタンスになります。

フロー実行の一時停止および中断時にユーザーからの入力を受信する方法の詳細については、
[フロー実行入力の送受信](/v3/develop/inputs/)を参照してください。